/*
 * Copyright (c) 2025 ArcesTeam. All rights reserved.
 * This project is licensed under the MIT License. See the LICENSE file for details.
 * This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the MIT License for more details.
 *
 */

plugins {
  id 'idea'
}

allprojects {
  group = mod_group_id
  version = mod_version

  repositories {
    mavenLocal()
    mavenCentral()
  }

  tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    sourceCompatibility = java_version
    targetCompatibility = java_version
  }
}

subprojects {
  apply plugin: 'idea'
  apply plugin: 'java-library'

  tasks.withType(Test).configureEach {
    useJUnitPlatform()
  }
}

idea {
  module {
    downloadSources = true
    downloadJavadoc = true
  }
}
