version: '3.9'

services:
  meta-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:workspace
      - gradle-cache:/home/gradle/.gradle
    working_dir: /workspace
    tty: true
    stdin_open: true

volumes:
  gradle-cache:
