#
# Copyright (c) 2025 ArcesTeam. All rights reserved.
# This project is licensed under the MIT License. See the LICENSE file for details.
# This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the MIT License for more details.
#
#
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
### Java ###
java_version=21
### Minecraft ###
minecraft_version=1.21.5
minecraft_version_range=[1.21.5]
### Mod ###
mod_id=meta
mod_name=Meta
mod_group_id=io.github.arcesteam.meta
mod_version=0.1.0
mod_license=MIT
mod_authors=TierneyJohn
mod_description=There is currently no relevant description.
### Dependencies version ###
slf4j_api_version=2.0.17
jetbrains_annotations_version=26.0.2
jupiter_version=5.12.2
