name: "📚️ 文档问题反馈"
description: "请认真填写本模板中的各项内容。您的反馈对项目改进至关重要，感谢您的支持！"
title: "[Doc]: "
labels:
  - Documentation
  - P3
type: Documentation
body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您为本项目贡献力量！

        为帮助我们更高效地处理您的反馈，请尽可能详细、准确地填写以下内容。

        - 提交前请查阅 [CONTRIBUTING](https://github.com/ArcesTeam/meta-dev/blob/main/.github/lang/zh-CN/CONTRIBUTING.md) 以了解贡献流程和要求。
        - 请遵守我们的 [行为准则](https://github.com/ArcesTeam/meta-dev/blob/main/.github/lang/zh-CN/CODE_OF_CONDUCT.md)，保持尊重与友善。
        - 提交前请先搜索现有 Issue，避免重复反馈。

        感谢您的理解与配合！🙏

  - type: markdown
    attributes:
      value: |
        ### 关于 📚️ 文档问题反馈

        本模板专用于反馈文档、注释、API 文档、WIKI 等相关问题。

        如有语言文件相关问题（如翻译、文本规范等），可访问 [Discussions](https://github.com/orgs/ArcesTeam/discussions) 的 i18n 板块进一步探讨。

        再次感谢您的支持！🙏

        ---

  - type: checkboxes
    id: doc-type
    attributes:
      label: "涉及范围"
      description: "请选择需调整的文档类型。"
      options:
        - label: "语言文件"
        - label: "代码注释"
        - label: "API 文档"
        - label: "项目文档"
        - label: "WIKI"

  - type: textarea
    id: detailed-description
    attributes:
      label: "问题描述"
      description: "请详细描述需更正的文本及原因。"
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: relevant-log-output
    attributes:
      label: "相关文本/代码（可选）"
      description: "请粘贴与文档问题相关的文本、代码或其他信息。内容将自动格式化。"
      render: shell
    validations:
      required: false

  - type: input
    id: contact-details
    attributes:
      label: "联系方式（可选）"
      description: "如需进一步沟通，我们可通过哪些方式联系您？"
      placeholder: "如：email@example.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        提交 Issue 后，您可继续通过评论上传截图或其他附件（如 xx.log）。

  - type: markdown
    attributes:
      value: |
        ---

        ### 行为准则声明

        提交本 Issue 即表示您同意遵守我们的[行为准则](https://github.com/ArcesTeam/meta-dev/blob/main/.github/lang/zh-CN/CODE_OF_CONDUCT.md)。
        感谢您保持友善与尊重！

        ✅ 我同意遵守本项目的行为准则。

        ---

